version: '3'

services:
  db-postgres-evento:
    image: bitnami/postgresql
    ports:
      - "5432:5432"
    container_name: "db-postgres-evento"
    volumes:
      - ./banco-de-dados-evento:/var/lib/postgresql/data
    environment:
      POSTGRESQL_USERNAME: pguser
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_DATABASE: ignitenode03

